---
- name: Ip Geolocation Locator Deployment
  hosts: iplocation
  become: yes

  tasks:
    - name: Make Sure Docker Is Installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Run Docker Image
#      shell: "docker run --restart always -p 80:80 davidgman/iplocation:{{ tag }} -i 8.8.8.8"
       shell: 'docker run -v "${PWD}":/work:ro --rm davidgman/iplocation:{{ tag }} -i 8.8.8.8'


